const assert = require('assert');
const band = require('../app/generated/logic.js');
const song = band.emptySong();
const mutes = band.emptyMutes();
assert.equal(band.voiceAudible(mutes, 'kick'), true);
assert.equal(band.validateVelocity(100), 100); assert.equal(band.validateVelocity(0), 0); assert.equal(band.validateVelocity(42.6), 43);
assert.equal(band.velocityGain(0.16, 100), 0.16); assert.equal(band.velocityGain(0.16, 0), 0); assert.equal(band.velocityGain(0.16, 50), 0.08);
assert.throws(() => band.validateVelocity(-1), /0..100/); assert.throws(() => band.validateVelocity(101), /0..100/); assert.throws(() => band.validateVelocity(Infinity), /0..100/); assert.throws(() => band.velocityGain(-0.1, 100), /nonnegative/);
assert.equal(band.validateSwing(0), 0); assert.equal(band.validateSwing(45), 45); assert.equal(band.validateSwing(12.6), 13);
assert.equal(band.stepIntervalMs(120, 0, 0), band.stepMs(120)); assert.equal(band.stepIntervalMs(120, 1, 0), band.stepMs(120));
const swungPair = band.stepIntervalMs(120, 0, 45) + band.stepIntervalMs(120, 1, 45); assert.equal(swungPair, band.stepMs(120) * 2);
assert.throws(() => band.validateSwing(-1), /0..45/); assert.throws(() => band.validateSwing(46), /0..45/); assert.throws(() => band.validateSwing(NaN), /0..45/); assert.throws(() => band.stepIntervalMs(120, -1, 0), /nonnegative/);
const mutedKick = band.toggleMute(mutes, 'kick');
assert.equal(band.voiceAudible(mutedKick, 'kick'), false);
assert.equal(band.voiceAudible(mutedKick, 'snare'), true);
assert.equal(band.voiceAudible(mutes, 'kick'), true);
assert.equal(band.voiceScheduled(mutes, 'kick', 100), true); assert.equal(band.voiceScheduled(mutes, 'kick', 0), false); assert.equal(band.voiceScheduled(mutedKick, 'kick', 100), false);
const rotationSource = { kick: [true, false, true, false].concat(Array(12).fill(false)), snare: Array(16).fill(false), hat: Array(16).fill(false) };
const rotatedLeft = band.rotateVoice(rotationSource, 'kick', 'left');
assert.equal(rotatedLeft.kick[15], true); assert.equal(rotatedLeft.kick.filter(Boolean).length, 2);
assert.deepEqual(band.rotateVoice(rotatedLeft, 'kick', 'right'), rotationSource);
let history = band.createHistory(song, 96);
history = band.editHistory(history, {song: band.toggle(song, 'kick', 0), tempo: 96});
assert.equal(history.past.length, 1); assert.equal(history.present.song.kick[0], true);
const undone = band.undoHistory(history);
assert.equal(undone.present.song.kick[0], false); assert.equal(undone.future.length, 1);
const redone = band.redoHistory(undone);
assert.equal(redone.present.song.kick[0], true); assert.equal(redone.future.length, 0);
assert.strictEqual(band.editHistory(history, {song: history.present.song, tempo: 96}), history);
let bounded = band.createHistory(song, 96);
for (let i = 0; i < 55; i++) bounded = band.editHistory(bounded, {song: band.toggle(bounded.present.song, 'kick', i % band.STEP_COUNT), tempo: 96});
assert.equal(bounded.past.length, 50);
assert.equal(band.editHistory(undone, {song: band.toggle(undone.present.song, 'snare', 1), tempo: 96}).future.length, 0);
assert.equal(song.kick.length, 16);
const toggled = band.toggle(song, 'kick', 3);
assert.equal(toggled.kick[3], true); assert.equal(song.kick[3], false);
assert.equal(band.stepMs(120), 250);
assert.throws(() => band.validateTempo(59), /60..180/);
assert.throws(() => band.toggle(song, 'hat', 16), /0..15/);
assert.deepEqual(band.navigateGrid(0, 0, 'ArrowRight'), { row: 0, column: 1 });
assert.deepEqual(band.navigateGrid(0, 0, 'ArrowUp'), { row: 0, column: 0 });
assert.deepEqual(band.navigateGrid(1, 15, 'ArrowDown'), { row: 2, column: 15 });
assert.deepEqual(band.navigateGrid(2, 15, 'ArrowRight'), { row: 2, column: 15 });
assert.deepEqual(band.navigateGrid(1, 8, 'Home'), { row: 1, column: 0 });
assert.deepEqual(band.navigateGrid(1, 8, 'End'), { row: 1, column: 15 });
const preset = band.preset('Saucepan Parade');
preset.song.kick[0] = false;
assert.equal(band.PRESETS['Saucepan Parade'].song.kick[0], true);
const cleared = band.clearSong();
assert.equal(cleared.kick.concat(cleared.snare, cleared.hat).filter(Boolean).length, 0);
assert.throws(() => band.preset('Not a real band'), /unknown preset/);
const exported = band.exportPattern(preset.song, preset.tempo);
const imported = band.importPattern(exported);
assert.deepEqual(imported.song, preset.song); assert.equal(imported.tempo, preset.tempo);
assert.throws(() => band.importPattern(JSON.stringify({schema: 1, tempo: 96, song: {kick: Array(16).fill('x'), snare: Array(16).fill(false), hat: Array(16).fill(false)}})), /sixteen booleans/);
assert.throws(() => band.importPattern(JSON.stringify({schema: 1, tempo: 96, song: {kick: Array(8).fill(false), snare: Array(8).fill(false), hat: Array(8).fill(false)}, extra: true})), /only schema/);
assert.throws(() => band.importPattern('null'), /only schema/);
assert.throws(() => band.importPattern('{"__proto__": {}}'), /only schema/);
assert.throws(() => band.importPattern('x'.repeat(8193)), /8192/);
assert.equal(band.normalizeSaveName('  Tuesday kitchen  '), 'Tuesday kitchen');
assert.throws(() => band.normalizeSaveName(''), /1..40/);
assert.throws(() => band.normalizeSaveName('x'.repeat(41)), /1..40/);
const savedRaw = band.exportSave(' Tuesday kitchen ', preset.song, preset.tempo);
const saved = band.importSave(savedRaw);
assert.equal(saved.name, 'Tuesday kitchen'); assert.deepEqual(saved.song, preset.song); assert.equal(saved.tempo, preset.tempo);
assert.throws(() => band.importSave(JSON.stringify({schema: 1, name: 'x', tempo: 96, song: preset.song, extra: true})), /schema/);
let slots = {};
slots[saved.name] = saved;
const library = band.importSaveCollection(band.exportSaveCollection(slots));
assert.deepEqual(library.slots['Tuesday kitchen'].song, preset.song);
const ten = {};
for (let i = 0; i < 10; i++) ten[`slot${i}`] = band.importSave(band.exportSave(`slot${i}`, song, 96));
assert.equal(Object.keys(band.importSaveCollection(band.exportSaveCollection(ten)).slots).length, 10);
ten.extra = band.importSave(band.exportSave('extra', song, 96));
assert.throws(() => band.exportSaveCollection(ten), /10/);
assert.throws(() => band.importSaveCollection(JSON.stringify({schema: 1, slots: {bad: {schema: 1, name: 'other', tempo: 96, song}}})), /mismatch/);
const oddName = band.importSave(band.exportSave('__proto__', song, 96));
const oddSlots = Object.create(null); oddSlots['__proto__'] = oddName;
assert.equal(band.importSaveCollection(band.exportSaveCollection(oddSlots)).slots['__proto__'].name, '__proto__');
console.log('pattern logic checks passed');
