const assert = require('assert');
const band = require('../app/generated/logic.js');
const song = band.emptySong();
assert.equal(song.kick.length, 8);
const toggled = band.toggle(song, 'kick', 3);
assert.equal(toggled.kick[3], true); assert.equal(song.kick[3], false);
assert.equal(band.stepMs(120), 250);
assert.throws(() => band.validateTempo(59), /60..180/);
assert.throws(() => band.toggle(song, 'hat', 8), /0..7/);
const preset = band.preset('Saucepan Parade');
preset.song.kick[0] = false;
assert.equal(band.PRESETS['Saucepan Parade'].song.kick[0], true);
const cleared = band.clearSong();
assert.equal(cleared.kick.concat(cleared.snare, cleared.hat).filter(Boolean).length, 0);
assert.throws(() => band.preset('Not a real band'), /unknown preset/);
console.log('pattern logic checks passed');
